#
# Docker generic base image for GitLab-CI
#
# Written by:
#   Baptiste MOINE <contact@bmoine.fr>
#

version: '3'
networks: {}
services:
    dind:
        build: .
        image: creased/docker-dind:latest
volumes: {}
